name: Imprime data atual do Silao

on:
  push:
  
jobs:
  imprime_data_ubuntu:
    name: Imprime data atual
    runs-on: ubuntu-latest
  
    steps:
      - name: Imprime data atual - Ubuntu
        run: date
